# Generated by Django 4.1.1 on 2022-09-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
